### ISSUE TITLE
"there is a hard limit of 256 sidechains identified as 0-255"

### ISSUE THREAD

**Issue by gubatron** [drivechain-project/docs#13]
why such a limited number, why not at least 2 bytes for 65k possibilities?
256 sidechain projects will come about in no time if this standard sticks

**Comment by psztorc** [comment]
There really is no limit, because if you have a mainchain and 256 sidechains, you can then soft fork drivechain itself into one of those original 256 sidechains. You can then have an unbounded number of total sidechains.
